In [ ]:
%load_ext autoreload
%autoreload 2

In [6]:
# Importing libraries

from src.data.wrangler import get_close_prices, data_wrangler, get_kept_tickers, retention_ratio
from src.data.returns import get_log_returns, get_simple_returns

import warnings
warnings.filterwarnings('ignore')

In [8]:
log_returns = get_log_returns()
log_returns.head(5)

Loading local data...

Ticker,ABG.JO,ACT.JO,ADH.JO,AFT.JO,AGL.JO,AIP.JO,AME.JO,ANG.JO,APN.JO,ART.JO,...,SLM.JO,SNT.JO,SPG.JO,SPP.JO,TFG.JO,TKG.JO,TRU.JO,VOD.JO,WBO.JO,WHL.JO
Date,,,,,,,,,,,,,,,,,,,,,
2006-11-08,-0.000703,-0.096627,0.018349,0.012121,-0.014193,0.026038,-0.024571,0.011751,-0.009274,0.006042,...,0.009570,0.005641,0.000000,0.002719,0.022871,0.017201,0.015504,0.017201,0.000713,0.001889
2006-11-09,-0.015511,0.067252,0.003630,0.023811,-0.018214,-0.013032,0.000000,-0.008604,-0.007794,0.017911,...,0.001679,0.003992,-0.008097,0.012023,0.002914,-0.002429,0.001431,-0.002429,0.003417,-0.010750
2006-11-10,-0.015211,0.026740,-0.018282,0.045985,0.019610,0.003242,0.000000,0.013266,-0.001566,-0.017911,...,-0.027213,-0.002368,-0.012270,0.024097,0.000182,0.007615,-0.012222,0.007616,0.000000,-0.001909
2006-11-13,0.020112,0.002635,0.011010,-0.011300,-0.025111,-0.009756,0.000000,-0.024801,0.003130,-0.009077,...,0.001149,0.005848,-0.004124,-0.004773,-0.004738,-0.038669,-0.018985,-0.038669,-0.015760,-0.009600
2006-11-14,0.003992,0.013072,0.000000,-0.017192,-0.001342,0.006450,0.000000,0.024026,0.016119,0.011484,...,0.013117,0.004950,0.020451,0.018723,0.013606,-0.025410,0.017176,-0.025410,0.010772,0.022259

In [9]:
log_returns.tail(5)

Ticker,ABG.JO,ACT.JO,ADH.JO,AFT.JO,AGL.JO,AIP.JO,AME.JO,ANG.JO,APN.JO,ART.JO,...,SLM.JO,SNT.JO,SPG.JO,SPP.JO,TFG.JO,TKG.JO,TRU.JO,VOD.JO,WBO.JO,WHL.JO
Date,,,,,,,,,,,,,,,,,,,,,
2024-12-23,-0.013828,0.068993,-0.003362,0.006903,0.021679,0.028064,0.000000,-0.002290,0.002414,0.001091,...,0.015739,-0.001353,-0.007186,0.010949,-0.009031,0.004112,0.005945,0.002873,-0.005744,-0.008658
2024-12-24,0.006730,-0.045462,-0.007684,0.002004,0.010225,-0.007809,0.000000,0.013344,-0.012710,0.001816,...,0.007322,-0.008368,0.019385,-0.004962,0.002222,-0.003523,0.005530,0.005820,0.001508,0.011527
2024-12-27,-0.011032,-0.033100,0.002773,0.000858,0.011030,0.020444,-0.110309,-0.011839,-0.011696,0.000000,...,-0.015508,0.003670,-0.023514,-0.010200,-0.021308,0.007618,-0.033843,0.006666,0.023952,-0.012655
2024-12-30,-0.000263,-0.014528,0.007663,-0.001859,-0.007639,-0.007264,0.050644,-0.019923,-0.022125,-0.010949,...,0.000579,0.005974,0.003442,-0.008952,-0.003586,-0.001753,-0.000984,-0.008537,-0.015813,-0.006145
2024-12-31,-0.002158,-0.029705,0.032741,0.015625,0.009852,-0.003129,0.000000,-0.006841,-0.008637,0.011312,...,0.005193,0.020975,0.013652,-0.012381,0.005946,0.022265,0.019787,-0.001183,0.054758,0.011290